### ISSUE TITLE
Want to take over the project

### ISSUE THREAD

**Issue by ricardopiloto** [Nevenall/foundry-shadowrun6e#5]
Hi Nevenall,
I'm new to programming but I'm willing to take over the project as a way of learning web development as part of my free time. How can we arrange this?

Thanks,
Ricardo.

**Comment by Nevenall** [comment]
Hey! Sorry about missing your issue for so long. I'm going to archive this repo in favor of https://bitbucket.org/rpgframework-cloud/shadowrun6-eden/src/master/. 
But if you want I believe I can still transfer it to you.
